# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `actionpack-action_caching` gem.
# Please instead update this file by running `bin/tapioca gem actionpack-action_caching`.

# source://actionpack-action_caching//lib/actionpack/action_caching/railtie.rb#3
module ActionPack
  class << self
    # source://actionpack/7.2.0.alpha-b1d57fb8c87d771d9a74ac31cd9969e6806b03b2/lib/action_pack/gem_version.rb#5
    def gem_version; end

    # source://actionpack/7.2.0.alpha-b1d57fb8c87d771d9a74ac31cd9969e6806b03b2/lib/action_pack/version.rb#7
    def version; end
  end
end

# source://actionpack-action_caching//lib/actionpack/action_caching/railtie.rb#4
module ActionPack::ActionCaching; end

# source://actionpack-action_caching//lib/actionpack/action_caching/railtie.rb#5
class ActionPack::ActionCaching::Railtie < Rails::Railtie; end
