# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dedup` gem.
# Please instead update this file by running `bin/tapioca gem dedup`.

# source://dedup//lib/dedup/version.rb#3
module Dedup
  extend ::Dedup::Native
end

# source://dedup//lib/dedup/version.rb#6
Dedup::DEDUP_FROZEN_STRINGS = T.let(T.unsafe(nil), TrueClass)

# source://dedup//lib/dedup/version.rb#11
Dedup::DEDUP_HASH_ASET = T.let(T.unsafe(nil), TrueClass)

# source://dedup//lib/dedup/version.rb#20
Dedup::DEDUP_HASH_ASET_FROZEN = T.let(T.unsafe(nil), FalseClass)

# source://dedup//lib/dedup.rb#7
Dedup::EMPTY_ARRAY = T.let(T.unsafe(nil), Array)

# source://dedup//lib/dedup.rb#6
Dedup::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# source://dedup//lib/dedup.rb#8
class Dedup::Error < StandardError; end

module Dedup::Native
  extend ::Dedup::Native

  def deep_intern!(_arg0); end
end

# source://dedup//lib/dedup.rb#10
module Dedup::Ruby
  extend ::Dedup::Ruby

  # source://dedup//lib/dedup.rb#14
  def deep_intern!(data); end
end

# source://dedup//lib/dedup/version.rb#4
Dedup::VERSION = T.let(T.unsafe(nil), String)
