inherit_from:
  - https://raw.githubusercontent.com/gmcgibbon/dotfiles/main/rubocop.yml

AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - bin/bundle

require:
  - "./lib/cops/active_support_deprecation_usage"
  - rubocop-rails
  - rubocop-minitest

Minitest/MultipleAssertions:
  Enabled: false
