inherit_from:
  - https://raw.githubusercontent.com/gmcgibbon/dotfiles/main/rubocop.yml

require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.3.0
  Exclude:
    - bin/bundle
