inherit_from:
  - https://raw.githubusercontent.com/gmcgibbon/dotfiles/main/rubocop.yml

require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.3.0
  Exclude:
    - bin/bundle

Style/ClassAndModuleChildren:
  Exclude:
    - sorbet

Sorbet/TrueSigil:
  Enabled: true
