gem:
  # Add your `gem` command parameters here:
  #
  exclude:
  - rubocop
  - rubocop-ast
  - rubocop-capybara
  - rubocop-sorbet
  - rubocop-rails
  - ast
  - parser
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
