require 'rails_helper'

RSpec.feature 'Logins', type: :feature do

  def login_as(user)
    click_link('Log in')

    fill_in('Email', with: user.email)
    fill_in('Password', with: '11111111')

    click_button('Log in')
  end

  describe 'user' do

    before { visit '/' }

    context 'as guest' do

      # not persisted, generated by faker
      let!(:user) { FactoryGirl.build(:user) }

      scenario 'authenticate' do

        login_as(user)

        expect(page).to have_content('Invalid email or password.')
        expect(page).to_not have_content('Admin')
      end

    end

    context 'as reader' do
      let!(:user) { FactoryGirl.create(:user, :reader) }

      scenario 'authenticate' do

        login_as(user)

        expect(page).to have_content('Signed in successfully.')
        expect(page).to_not have_content('Admin')
      end
    end

    context 'as admin' do

      let!(:user) { FactoryGirl.create(:user, :admin) }

      scenario 'authenticate' do

        login_as(user)

        expect(page).to have_content('Signed in successfully.')
        expect(page).to have_content('Admin')
      end
    end

  end

end
