# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in blog.gemspec.
gemspec

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false
gem "byebug", platforms: %i(mri mingw x64_mingw)

# View component rendering and testing
gem "capybara"
gem "importmap-rails"

gem "actionpack-action_caching"
gem "rails", github: "rails/rails"

gem "sorbet-runtime"
